import {
	setAddress,
	setLoggedIn,
	setStrikePrice,
	setPremium,
	setQuantity,
	setExpiry,
	setLoadingStrike,
	setLoadingPremium,
	setLoadingQuantity,
	setLoadingExpiry,
	setStrikePriceC,
	setPremiumC,
	setQuantityC,
	setExpiryC,
	setLoadingStrikeC,
	setLoadingPremiumC,
	setLoadingQuantityC,
	setLoadingExpiryC,
	setError,
} from "./Reducers";
import { combineReducers } from "@reduxjs/toolkit";

const allReducers = combineReducers({
	address: setAddress,
	loggedIn: setLoggedIn,
	strikePrice: setStrikePrice,
	premium: setPremium,
	quantity: setQuantity,
	expiry: setExpiry,
	loadingStrike: setLoadingStrike,
	loadingPremium: setLoadingPremium,
	loadingQuantity: setLoadingQuantity,
	loadingExpiry: setLoadingExpiry,
	strikePriceC: setStrikePriceC,
	premiumC: setPremiumC,
	quantityC: setQuantityC,
	expiryC: setExpiryC,
	loadingStrikeC: setLoadingStrikeC,
	loadingPremiumC: setLoadingPremiumC,
	loadingQuantityC: setLoadingQuantityC,
	loadingExpiryC: setLoadingExpiryC,
	error: setError,
});
export default allReducers;
